spring:
  application:
    name: redis
server:
  port: 8080
redis:
  host: "${redis-host}"
  port: ${redis-port}
  user: "${redis-user}"
  secret: "${redis-secret}"
  jedis:
    pool:
      max-total: 16
      max-idle: 8
      min-idle : 4
